version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI: http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  users-service:
    build: ./users-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  orders-service:
    build: ./orders-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]

  payments-service:
    build: ./payments-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: [rabbitmq]
